name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Appium
      run: npm install -g appium

    - name: Start Appium server
      run: appium --log-level error &

    - name: Install Maven dependencies
      run: mvn clean install

    - name: Run tests
      run: mvn clean install -Dtest=FitnessPalTest

       

      
