name: Manual Test Execution

on:      
  push:
    branches:
      - master
      - 18Task
  pull_request:
  workflow_dispatch:
    inputs:
      report-type:
        description: 'Select Report Type'
        required: false
        options: 
          - daily
          - weekly
          - monthly

jobs:
  test:
    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
  appium:
    runs-on: ubuntu-latest
 
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Install and Run Appium Server
         uses: moatazeldebsy/appium-server-gitHub-action@V1.0.4

       - name: Build and Run Tests
         run: mvn clean install -Dtest=FitnessPalTest


       - name: Generate Report
         if: ${{ github.event.inputs.report-type }}
         run: echo "Generating ${REPORT_TYPE} report..."
