name: Manual Test Execution

on:      
  push:
    branches:
      - master
      - 18Task
  pull_request:
  workflow_dispatch:
    inputs:
      report-type:
        description: 'Select Report Type'
        required: true
        default: 'daily'
        options: 
          - daily
          - weekly
          - monthly

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Build and Run Tests
        run: mvn clean test

      - name: Generate Daily Report
        if: ${{ github.event.inputs.report-type == 'daily' }}
        run: echo "Generating daily report..."

      - name: Generate Weekly Report
        if: ${{ github.event.inputs.report-type == 'weekly' }}
        run: echo "Generating weekly report..."
        
      - name: Generate Monthly Report
        if: ${{ github.event.inputs.report-type == 'monthly' }}
        run: echo "Generating monthly report..."
