name: Run Android tests

on:
  workflow_dispatch:

jobs:
  run-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Pull the project into the runner
        uses: actions/checkout@v3

      - name: Setup Appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &

      - name: Kill ADB server
        run: adb kill-server

      - name: Start ADB server
        run: adb start-server

      - name: Run Appium Android tests
        run: mvn clean test -Dtest=FitnessPalTest#loginSimpleUserTest
        timeout-minutes: 10

