name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: mvn clean install

    - name: Start Appium server
      run: npm install -g appium && appium --log-level error &

    - name: Run tests on device
      run: mvn clean install -Dtest=FitnessPalTest
