name: Manual Report Generation

on:
  workflow_dispatch:
    inputs:
      report_type:
        description: 'Select report type'
        required: true
        options: 
          - daily
          - weekly
          - monthly

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Java Tests
        run: |
          mvn clean test 


