name: Scheduled Test Execution

on:
  schedule:
     - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and Run Java Tests
        run: |
          mvn clean test
